### ISSUE TITLE
Unable to make and install radamsa

### ISSUE THREAD

**Issue by xyphanajay** [anestisb/radamsa-android#2]
Files are missing (or misplaced) as I am unable to make or install from radamsa-android dir.
The dir contains the following files and folders only:
**doc**  **jni**  LICENCE  NEWS  README.md  **tests**

**jni** folder contains 3 files, which can be used but no idea how.
Android.mk  Application.mk  radamsa.c

**Comment by anestisb** [comment]
Project can be build with ndk-build from Android NDK. From the project directory simply run `ndk-build`

```
$ ndk-build
[armeabi-v7a] Compile thumb  : radamsa <= radamsa.c
[armeabi-v7a] Executable     : radamsa
[armeabi-v7a] Install        : radamsa => libs/armeabi-v7a/radamsa
[arm64-v8a] Compile        : radamsa <= radamsa.c
[arm64-v8a] Executable     : radamsa
[arm64-v8a] Install        : radamsa => libs/arm64-v8a/radamsa
[x86] Compile        : radamsa <= radamsa.c
[x86] Executable     : radamsa
[x86] Install        : radamsa => libs/x86/radamsa
[x86_64] Compile        : radamsa <= radamsa.c
[x86_64] Executable     : radamsa
[x86_64] Install        : radamsa => libs/x86_64/radamsa
```

**Comment by xyphanajay** [comment]
Tried to find how to change armeabi to armeabi-v7a, no luck. First time dealing with NDK.
I am using Manjaro, updated $PATH (added /home/../Android/ndk-bundle).

I am getting this error
`Android NDK: The armeabi ABI is no longer supported. Use armeabi-v7a.    
Android NDK: NDK Application 'local' targets unknown ABI(s): armeabi    
Android NDK: Please fix the APP_ABI definition in ./jni/Application.mk    
/home/kaneki/Android/ndk-bundle/build/core/setup-app.mk:79: *** Android NDK: Aborting    .  Stop`

Need help!

**Comment by anestisb** [comment]
Since armeabi is no longer supported from recent Android NDKs it has been removed in https://github.com/anestisb/radamsa-android/commit/40d13497c901ec20541e43914a90c96e448c3b33. Checkout latest master and you should be ok.

**Comment by xyphanajay** [comment]
Successfully built radamsa but 
`$ radamsa`
`bash: radamsa: command not found`
`$ ./libs/x86_64/radamsa   `
`bash: ./libs/x86_64/radamsa: No such file or directory`
`$ ./libs/arm64-v8a/radamsa `
`bash: ./libs/arm64-v8a/radamsa: cannot execute binary file: Exec format error`
`$ ./libs/armeabi-v7a/radamsa `
`bash: ./libs/armeabi-v7a/radamsa: cannot execute binary file: Exec format error`

elf is available in libs/x86_64
`$ binwalk libs/x86_64/radamsa `

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             ELF, 64-bit LSB shared object, AMD x86-64, version 1 (SYSV)

**Comment by anestisb** [comment]
The build output is a standalone binary intended to run on Android devices and not a Linux workstation. If you want to run radamsa on your Linux machine, compile it from the official project.
