### ISSUE TITLE
[Question] Occur "Segmentation fault" in a device

### ISSUE THREAD

**Issue by moon2263** [anestisb/radamsa-android#4]
Hi! I tried it to my Galaxy Note 4 (Android 6.0.1) which is already rooted. 
I pushed the binary which is compiled to armeabi-v7a using ndk-build into the device. But when I executed the binary in adb shell, it occurs segmentation fault. 
How can I solve this problem..?

Thank you in advance!

**Comment by anestisb** [comment]
Can you share the crash stack trace? Without it I have no obvious way to debug the issue. Also give latest master a try as I ported latest upstream.

**Comment by moon2263** [comment]
I try the latest version and it worked Thank you very much. Just what I did, in addition, was to modify APP_PLATFORM android-28 to android-23 in Application.mk. Because my device is Android 6.0.1. Anyway, thank you for your patch.
